test3/new_car/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('perziura.urls')),
    # path('perziura/', include('perziura.urls')),
    # path('registracija/', include('registracija.urls')),

    # path('persons/', include('perziura.urls'))
]

test3/perziura/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.pradinis, name='pradinis'),
    path('perziura/', views.Perziura.as_view(), name='perziura'),
    path('registracija/', views.Registracija.as_view(), name='registracija'),
    # path('ivykdyti/', views.Ivykdyti.as_view(), name='ivykdyti'),
    path('ivykdyti/', views.klientas_list_done, name='ivykdyti'),

    path('<int:pk>/', views.Redagavimas.as_view(), name='redagavimas'),
    path('pasalinimas/<int:pk>/', views.Pasalinimas.as_view(), name='pasalinimas'),


    path('ajax/load-modeliai/', views.load_modeliai, name='ajax_load_modeliai'),
    path('ajax/load-spalvos/', views.load_spalvos, name='ajax_load_spalvos'),
    path('ajax/load-metais/', views.load_metais, name='ajax_load_metais'),
]

test3/registracija/urls.py
from django.urls import path
from . import views

urlpatterns = [

    
    # path('persons/add/', views.registracija, name='registracija'),
    # path('persons/add/', views.person_create_view, name='person_add'),
]

test3/perziura/models.py
from django.db import models

from tkinter import TRUE
from django.db import models
import datetime


class Marke(models.Model):
    marke = models.CharField(max_length=20, null=True, blank=True, default='marke')
    def __str__(self):
        # return self.marke  
        return '{}'.format(self.marke) 
                           

class Modelis(models.Model):
    modelis = models.CharField(max_length=20, null=True, blank=True, default='modelis')
    marke = models.ForeignKey(Marke, on_delete=models.CASCADE, null=True)
    def __str__(self):
        # return self.modelis 
        return '{}'.format(self.modelis)
      

class Metai(models.Model):
    metai = models.CharField(max_length=20, null=True, blank=True, default='metai')
    modelis = models.ForeignKey(Modelis, on_delete=models.CASCADE, null=True)
    def __str__(self):
        # return self.metai 
        return '{}'.format(self.metai)

      
class Spalva(models.Model):
    spalva = models.CharField(max_length=20, null=True, blank=True, default='spalva')
    modelis = models.ForeignKey(Modelis, on_delete=models.CASCADE, null=True)
    def __str__(self):
        # return self.spalva 
        return '{}'.format(self.spalva)


class Klientas(models.Model):
    ivykdytas = models.BooleanField(verbose_name="ivykdytas", default=False)
    klientas_vardas = models.CharField(max_length=124, blank=True, null=True)
    klientas_pavarde = models.CharField(max_length=124, blank=True, null=True)
    klientas_email = models.CharField(max_length=30, blank=True, null=True)
    marke = models.ForeignKey(Marke, on_delete=models.SET_NULL, null=True)
    modelis = models.ForeignKey(Modelis, on_delete=models.SET_NULL, null=True)
    metai = models.ForeignKey(Metai, on_delete=models.SET_NULL, null=True)
    spalva = models.ForeignKey(Spalva, on_delete=models.SET_NULL, null=True)
    def __str__(self):
        # return self.klientas_vardas
        return '{}'.format(self.klientas_vardas)

test3/registracija/models.py
from django.db import models

# Create your models here.

test3/perziura/forms.py
# from django import forms

# # from .models import Person, City

# from .models import Order, Modelis


# class PersonCreationForm(forms.ModelForm):
#     class Meta:
#         model = Order
#         fields = '__all__'

#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.fields['modelis'].queryset = Modelis.objects.none()

#         if 'marke' in self.data:
#             try:
#                 marke_id = int(self.data.get('marke'))
#                 self.fields['modelis'].queryset = Modelis.objects.filter(marke_id=marke_id).order_by('modelis')
#             except (ValueError, TypeError):
#                 pass  # invalid input from the client; ignore and fallback to empty City queryset
#         elif self.instance.pk:
#             self.fields['modelis'].queryset = self.instance.marke.modelis_set.order_by('name')


from django import forms

# from .models import Person, City

from .models import Klientas, Marke, Modelis, Metai, Spalva


class PersonForm(forms.ModelForm):
    class Meta:
        model = Klientas
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['modelis'].queryset = Modelis.objects.none()
        # self.fields['metai'].queryset = Metai.objects.none()
        # self.fields['spalva'].queryset = Spalva.objects.none()

        

        if 'marke' in self.data:
            try:
                marke_id = int(self.data.get('marke'))
                # modelis_id = int(self.data.get('modelis'))
                self.fields['modelis'].queryset = Modelis.objects.filter(marke_id=marke_id).order_by('modelis')
                # self.fields['metai'].queryset = Metai.objects.filter(modelis_id=modelis_id).order_by('metai')
                # self.fields['spalva'].queryset = Spalva.objects.filter(modelis_id=modelis_id).order_by('spalva')
            except (ValueError, TypeError):
                print('except valueroor1111')
                pass 
      # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['modelis'].queryset = self.instance.marke.modelis_set.order_by('modelis')
            # self.fields['modelis'].queryset = self.instance.marke.modelis_set.order_by('modelis')
            # self.fields['metai'].queryset = self.instance.modelis.metai_set.order_by('metai')
            # self.fields['spalva'].queryset = self.instance.modelis.spalva_set.order_by('spalva')
      
      #   if 'modelis' in self.data:
      #       try:
      #           modelis_id = int(self.data.get('modelis'))
      #           # modelis_id = int(self.data.get('modelis'))
      #           # self.fields['modelis'].queryset = Modelis.objects.filter(marke_id=marke_id).order_by('modelis')
      #           # self.fields['metai'].queryset = Metai.objects.filter(modelis_id=modelis_id).order_by('metai')
      #           # self.fields['spalva'].queryset = Spalva.objects.filter(modelis_id=modelis_id).order_by('spalva')
      #       except (ValueError, TypeError):
      #           print('except valueroor2222')
      #           pass 
      # # invalid input from the client; ignore and fallback to empty City queryset
      #   elif self.instance.pk:
      #       # self.fields['modelis'].queryset = self.instance.country.marke_set.order_by('name')
      #       # self.fields['modelis'].queryset = self.instance.marke.modelis_set.order_by('modelis')
      #       self.fields['metai'].queryset = self.instance.modelis.metai_set.order_by('metai')
      #       self.fields['spalva'].queryset = self.instance.modelis.spalva_set.order_by('spalva')

      #   if 'modelis' in self.data:
      #       try:
      #           modelis_id = int(self.data.get('modelis'))
      #           # modelis_id = int(self.data.get('modelis'))
      #           # self.fields['modelis'].queryset = Modelis.objects.filter(marke_id=marke_id).order_by('modelis')
      #           # self.fields['metai'].queryset = Metai.objects.filter(modelis_id=modelis_id).order_by('metai')
      #           # self.fields['spalva'].queryset = Spalva.objects.filter(modelis_id=modelis_id).order_by('spalva')
      #       except (ValueError, TypeError):
      #           print('except valueroor2222')
      #           pass 
      # # invalid input from the client; ignore and fallback to empty City queryset
      #   elif self.instance.pk:
      #       # self.fields['modelis'].queryset = self.instance.country.marke_set.order_by('name')
      #       # self.fields['modelis'].queryset = self.instance.marke.modelis_set.order_by('modelis')
      #       self.fields['spalva'].queryset = self.instance.modelis.spalva_set.order_by('spalva')

test3/perziura/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PersonForm
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from multiprocessing import context
from .models import Klientas, Marke, Modelis, Metai, Spalva
from django.urls import reverse_lazy



def pradinis(request):
    return render(request, 'perziura/pradinis.html')

# ################################################################
# class Ivykdyti(ListView):
#     model = Klientas
#     context_object_name = 'klientai'




# def ivykdyti(request):
#    listas = Klientas.objects.all()
#    return render(request, 'perziura/klientas_list_done.html', {'listas' : listas})

  
def klientas_list_done(request):
    klientai = Klientas.objects.all()
    context={'klientai': klientai}
    return render(request, '/perziura/klientas_list_done.html', context=context)



class Perziura(ListView):
    model = Klientas
    context_object_name = 'klientai'


# class Ivykdyti(ListView):
#     model = Klientas
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context_object_name = 'klientai'
#         return context
  

class Registracija(CreateView):
    model = Klientas
    form_class = PersonForm
    # fields = ('klientas_vardas', 'klientas_pavarde', 'klientas_email', 'klientas_spalva')
    success_url = reverse_lazy('perziura')


class Redagavimas(UpdateView):
    model = Klientas
    form_class = PersonForm
    # fields = ('klientas_vardas', 'klientas_pavarde', 'klientas_email', 'klientas_spalva')
    success_url = reverse_lazy('perziura')

class Pasalinimas(DeleteView):
    model = Klientas
    # form_class = PersonForm
    # fields = ('klientas_vardas', 'klientas_pavarde', 'klientas_email', 'klientas_spalva')
    success_url = reverse_lazy('perziura')



@csrf_exempt
def load_modeliai(request):
    marke_id = request.POST.get('marke_id')
    # print('marke_id', marke_id)
    # modeliai = Modelis.objects.filter(marke__marke__contains = marke_id).all()
    modeliai = Modelis.objects.filter(marke_id=marke_id).all()
    print('modeliai', modeliai)
    return render(request, 'perziura/options_modelis.html', {'modeliai': modeliai})
    #  def load_modeliai(request):
#     marke_id = request.POST.get('marke_id')
#     modeliai = Modelis.objects.filter(marke__marke__contains = marke_id)
#     return render(request, 'options_modelis.html', {'modeliai': modeliai})




@csrf_exempt
def load_metais(request):
    modelis_id = request.POST.get('modelis_id')
    # metais = Metai.objects.filter(modelis__modelis__contains = modelis_id)
    # modeliai = Modelis.objects.filter(ivykdytas=False).all()
    metais = Metai.objects.filter(modelis_id=modelis_id).all()
    print('metais', metais)
    return render(request, 'perziura/options_metai.html', {'metais': metais})



@csrf_exempt
def load_spalvos(request):
    modelis_id = request.POST.get('modelis_id')
    # modeliai = Modelis.objects.filter(ivykdytas=False).all()
    # spalvos = Spalva.objects.filter(modelis__modelis__contains = modelis_id)
    spalvos = Spalva.objects.filter(modelis_id=modelis_id).all()
    print('spalvos', spalvos)
    return render(request, 'perziura/options_spalvos.html', {'spalvos': spalvos})
    #return JsonResponse(list(modeliai.values('id', 'name')), safe=False)
    

test3/registracija/views.py
# from django.shortcuts import render
# from django.http import HttpResponse
# from perziura.models import Klientas, Marke, Modelis


# def registracija(request):
#     if request.method=='POST':
#         user_name = request.POST.get('user_name')
#         user_last_name = request.POST.get('last_name')
#         user_date = request.POST.get('date')
#         user_email = request.POST.get('email')
#         user_marke = request.POST.get('marke')
#         user_modelis = request.POST.get('modelis')
#         user_metai = request.POST.get('metai')
#         new = Klientas(vardas = user_name, pavarde = user_last_name, gimimo_data = user_date, email = user_email)
#         new.save()
#         marke = Marke(automobilio_marke = user_marke)
#         modelis = Modelis(automobilio_modelis = user_modelis)
#         metai = Metai(automobilio_pagaminimo_metai = user_metai)
#         marke.save()
#         modelis.save()
#         metai.save()
#         modelis.metai.add(metai)
#         marke.modelis.add(modelis)
#         new.marke.add(marke)
    
#         new.save()
#     print(request.META['USER'])
# #    return HttpResponse("Hello, world. You're at the registracija page.")
#     return render(request, 'registracija.html')

test3/perziura/templates/perziura/111perziura.html
{% extends 'base.html' %}
{% block content %}
<h3>Uzsakymu sąrašas</h3>

  <table class="table table-hover mt-5">
    <thead>
      <tr>
        <th scope="col">Vardas</th>
        <th scope="col">Pavardė</th>
        <th scope="col">Markė</th> 
        <th scope="col">Modelis</th>
        <th scope="col">Metai</th>
      </tr>
    </thead>
    <tbody>
      {% for klientas in klientai %}
    <tr>
        <td scope="row">{{klientas.vardas}}</td>
        <td >{{klientas.pavarde}}</td>
        <td>{{klientas.marke.first}}</td> 
        <td>{{klientas.marke.first.modelis.first}}</td>
        <td>{{klientas.marke.first.modelis.first.metai.first}}</td>
        {% comment %} <td scope="row">{{order.vardas}}</td>
        <td >{{order.pavarde}}</td>
        <td>{{order.marke.first}}</td> 
        <td>{{order.marke.first.modelis.first}}</td>
        <td>{{order.marke.first.modelis.first.metai.first}}</td>   {% endcomment %}
    </tr>
    {% endfor %}
    </tbody>
  </table>
  {% endblock content %}

test3/perziura/templates/perziura/111registracija.html
{% extends 'base.html' %}

{% block content %}
<body>
  <div class="container">





<h2>Registracija</h2>
  
<form method='post' id = 'personForm' > 
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
    <input type="submit" value="Submit">
    <a href="{% url 'pradinis' %}">Nevermind</a>
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
  $("#id_marke").change(function () {
    const url = $("#personForm").attr("data-modeliai-url");  // get the url of the `load_cities` view
    const markeId = $(this).val();

    $.post('/ajax/load-modeliai/', {
      'marke_id': markeId       // add the country id to the GET parameters
    },)
    .done(function( data ) {
      $("#id_modelis").html(data);
    });
  });


  
  
  $("#id_modelis").change(function () {
    var url = $("#personForm").attr("data-metais-url");
    var modelisId = $(this).val();  // get the selected country ID from the HTML input

      $.post('/ajax/load-metais/', {
        'modelis_id': modelisId      // add the country id to the GET parameters
      },)
      .done(function( data ) {
        $("id_#metai").html(data);
      });
    });


  $("#id_modelis").change(function () {
    var url = $("#personForm").attr("data-spalvos-url");
    var modelisId = $(this).val();  // get the selected country ID from the HTML input

    $.post('/ajax/load-spalvos/', {
      'modelis_id': modelisId       // add the country id to the GET parameters
    },)
    .done(function( data ) {
      $("#id_spalva").html(data);
    });
  });
  

</script>

</div>
</body>
{% endblock %}

test3/perziura/templates/perziura/klientas_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<body>
  <div class="container">

<form action="" method="post">{% csrf_token %}
    <p>Ar tikrai norite istrinti "{{ klientas.klientas_vardas }} {{klientas.klientas_pavarde }}" uzsakyma?</p>
    <input type="submit" value="Confirm" />
</form>

</div>
</body>
{% endblock %}

test3/perziura/templates/perziura/klientas_form.html
{% extends 'base.html' %}

{% block content %}
<body>
  <div class="container">





<h2>Registracija</h2>
  
<form method='post' id = 'personForm' > 
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
    <input type="submit" value="Submit">
    <a href="{% url 'pradinis' %}">Atsaukti</a>
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
  $("#id_marke").change(function () {
    const url = $("#personForm").attr("data-modeliai-url");  // get the url of the `load_cities` view
    const markeId = $(this).val();

    $.post('/ajax/load-modeliai/', {
      'marke_id': markeId       // add the country id to the GET parameters
    },)
    .done(function( data ) {
      $("#id_modelis").html(data);
    });
  });


  
  
  $("#id_modelis").change(function () {
    var url = $("#personForm").attr("data-metais-url");
    var modelisId = $(this).val();  // get the selected country ID from the HTML input

      $.post('/ajax/load-metais/', {
        'modelis_id': modelisId      // add the country id to the GET parameters
      },)
      .done(function( data ) {
        $("id_#metai").html(data);
      });
    });


  $("#id_modelis").change(function () {
    var url = $("#personForm").attr("data-spalvos-url");
    var modelisId = $(this).val();  // get the selected country ID from the HTML input

    $.post('/ajax/load-spalvos/', {
      'modelis_id': modelisId       // add the country id to the GET parameters
    },)
    .done(function( data ) {
      $("#id_spalva").html(data);
    });
  });
  

</script>

</div>
</body>
{% endblock %}

test3/perziura/templates/perziura/klientas_list.html
{% extends 'base.html' %}

{% block content %}

  
<h3>Uzsakymu sąrašas</h3>

<p>
  <a href="{% url 'registracija' %}">Add person</a>
</p>
{% csrf_token %}

<table border="1">
  <thead>
    <tr>
      <th>Vardas</th>
      <th>Pavarde</th>
      <th>El. pastas</th>
      <th>Marke</th>
      <th>Modelis</th>
      <th>Metai</th>
      <th>Spalva</th>
      <th>Pašalinti</th>

    </tr>
  </thead>
  <tbody>
    {% for klientas in klientai %}
    {% if klientas.ivykdytas == False %}
      <tr>

     

            <td><a href="{% url 'redagavimas' klientas.pk %}">{{ klientas.klientas_vardas }}</a></td>
            <td>{{ klientas.klientas_pavarde }}</td>
            <td>{{ klientas.klientas_email }}</td>
            <td>{{ klientas.marke }}</td>
            <td>{{ klientas.modelis }}</td>
            <td>{{ klientas.metai }}</td>
            <td>{{ klientas.spalva }}</td>
            <td>
      
           <a href="{% url 'pasalinimas' klientas.pk %}" class="btn btn-outline-danger btn-sm"> Pasalinti</a>
            </td>

   
     
      </tr>     
  {% endif %}
  {% empty %}
        <tr>
          <td colspan="7">No person in the database. <a href="{% url 'registracija' %}">Add the first person</a>.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}

test3/perziura/templates/perziura/klientas_list_done.html
{% extends 'base.html' %}

{% block content %}

  
<h3>Ivykdyti uzsakymai</h3>


{% csrf_token %}

<table border="1">
  <thead>
    <tr>
      <th>Vardas</th>
      <th>Pavarde</th>
      <th>El. pastas</th>
      <th>Marke</th>
      <th>Modelis</th>
      <th>Metai</th>
      <th>Spalva</th>
      <th>Pašalinti</th>

    </tr>
  </thead>
  <tbody>
    {% for klientas in klientai %}
    {% if klientas.ivykdytas == True %}
      <tr>

     

            <td><a href="{% url 'redagavimas' klientas.pk %}">{{ klientas.klientas_vardas }}</a></td>
            <td>{{ klientas.klientas_pavarde }}</td>
            <td>{{ klientas.klientas_email }}</td>
            <td>{{ klientas.marke }}</td>
            <td>{{ klientas.modelis }}</td>
            <td>{{ klientas.metai }}</td>
            <td>{{ klientas.spalva }}</td>
            <td>
      
           <a href="{% url 'pasalinimas' klientas.pk %}" class="btn btn-outline-danger btn-sm"> Pasalinti</a>
            </td>

   
     
      </tr>     
  {% endif %}
  {% empty %}
        <tr>
          <td colspan="7">No person in the database. <a href="{% url 'registracija' %}">Add the first person</a>.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}

test3/perziura/templates/perziura/options_metai.html
<option value="">Pasirinkite</option>
{% for metai in metais %}
<option value="{{ metai.pk }}">{{ metai.metai }}</option>
{% endfor %}

test3/perziura/templates/perziura/options_modelis.html
<option value="">Pasirinkite</option>
{% for modelis in modeliai %}
<option value="{{ modelis.pk }}">{{ modelis.modelis }}</option>
{% endfor %}

test3/perziura/templates/perziura/options_spalvos.html
<option value="">Pasirinkite</option>
{% for spalva in spalvos %}
<option value="{{ spalva.pk }}">{{ spalva.spalva }}</option>
{% endfor %}

test3/perziura/templates/perziura/perziura.html
{% extends 'base.html' %}
{% block content %}
<h3>Uzsakymu sąrašas</h3>

  <table class="table table-hover mt-5">
    <thead>
      <tr>
        <th scope="col">Vardas</th>
        <th scope="col">Pavardė</th>
        <th scope="col">Markė</th> 
        <th scope="col">Modelis</th>
        <th scope="col">Metai</th>
      </tr>
    </thead>
    <tbody>
      {% for klientas in klientai %}
    <tr>
        <td scope="row">{{klientas.vardas}}</td>
        <td >{{klientas.pavarde}}</td>
        <td>{{klientas.marke.first}}</td> 
        <td>{{klientas.marke.first.modelis.first}}</td>
        <td>{{klientas.marke.first.modelis.first.metai.first}}</td>
        {% comment %} <td scope="row">{{order.vardas}}</td>
        <td >{{order.pavarde}}</td>
        <td>{{order.marke.first}}</td> 
        <td>{{order.marke.first.modelis.first}}</td>
        <td>{{order.marke.first.modelis.first.metai.first}}</td>   {% endcomment %}
    </tr>
    {% endfor %}
    </tbody>
  </table>
  {% endblock content %}

test3/perziura/templates/perziura/pradinis.html
{% extends 'base.html' %}
{% block content %}
<h3>Pradzia</h3>
<a class="button" href="registracija">Registracija</a>
<a class="button" href="perziura">Uzsakymai</a>
<a class="button" href="ivykdyti">Ivykdyti uzsakymai</a>
{% endblock content %}

test3/perziura/templates/perziura/registracija.html
{% extends 'base.html' %}

{% block content %}
<body>
  <div class="container">





<h2>Registracija</h2>
  
<form method='post' id = 'personForm' > 
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
    <input type="submit" value="Submit">
    <a href="{% url 'pradinis' %}">Nevermind</a>
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
  $("#id_marke").change(function () {
    const url = $("#personForm").attr("data-modeliai-url");  // get the url of the `load_cities` view
    const markeId = $(this).val();

    $.post('/ajax/load-modeliai/', {
      'marke_id': markeId       // add the country id to the GET parameters
    },)
    .done(function( data ) {
      $("#id_modelis").html(data);
    });
  });


  
  
  $("#id_modelis").change(function () {
    var url = $("#personForm").attr("data-metais-url");
    var modelisId = $(this).val();  // get the selected country ID from the HTML input

      $.post('/ajax/load-metais/', {
        'modelis_id': modelisId      // add the country id to the GET parameters
      },)
      .done(function( data ) {
        $("id_#metai").html(data);
      });
    });


  $("#id_modelis").change(function () {
    var url = $("#personForm").attr("data-spalvos-url");
    var modelisId = $(this).val();  // get the selected country ID from the HTML input

    $.post('/ajax/load-spalvos/', {
      'modelis_id': modelisId       // add the country id to the GET parameters
    },)
    .done(function( data ) {
      $("#id_spalva").html(data);
    });
  });
  

</script>

</div>
</body>
{% endblock %}